[package]
name = "automap"
version = "0.0.1"
authors = ["Michael Dougherty <maackle.d@gmail.com>"]
edition = "2018"

[dependencies]
cfg-if = "1.0"
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"], optional = true }
shrinkwraprs = "0.3"
